version: "3.3"

services:
  camera-worker:
    build:
      context: ./camera-worker
    volumes:
      - type: bind
        source: ./camera-worker/snapshots
        target: /usr/src/app/snapshots
    networks:
        - main
  feed-manager-fe:
    build:
      context: ./feed-manager-fe
    environment:
      REACT_APP_BACKEND_PORT: 14001
    ports:
      - 3080:80
    networks:
        - main
  feed-manager-be:
    build:
      context: ./feed-manager-be
    volumes:
      - type: bind
        source: ./camera-worker/snapshots
        target: /app/snapshots
    environment:
      JWT_SECRET: $JWT_SECRET
    ports:
      - 14001:4000
    networks:
        - main
networks:
  main:
    driver: bridge
